[server]
host = "0.0.0.0"
port = 8000

[models.act-fold]
display_name = "ACT Full Fold"
policy_repo_id = "data/outputs/jhimmens_linique-act-v2/pretty-elevator-4/final"
dataset_repo_id = "jhimmens/linique-v2"
task = "full-fold-v1"
device = "cuda"
temporal_ensemble_coeff = 0.01

[models.pi0-pickup]
display_name = "Pi0 Pickup"
policy_repo_id = "data/outputs/pi0-pickup/final"
dataset_repo_id = "jhimmens/linique-v2-pickup"
task = "pickup"
device = "cuda"
